/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Equipe02;


/**
 *
 * @author Ruban
 */
public class menus extends javax.swing.JFrame {

    /**
     * Creates new form menus
     */
    public menus() {
        
        this.setUndecorated(true);
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menus = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnmenuon = new javax.swing.JButton();
        btnreserv = new javax.swing.JButton();
        btnsalle = new javax.swing.JButton();
        btnstock = new javax.swing.JButton();
        btndeco = new javax.swing.JButton();
        titre = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        menu1 = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menus.setBackground(new java.awt.Color(247, 244, 227));
        menus.setPreferredSize(new java.awt.Dimension(284, 1080));
        menus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menus.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        btnmenuon.setBackground(new java.awt.Color(247, 244, 227));
        btnmenuon.setBorder(null);
        btnmenuon.setContentAreaFilled(false);
        btnmenuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuonActionPerformed(evt);
            }
        });
        menus.add(btnmenuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 225, -1, -1));

        btnreserv.setBackground(new java.awt.Color(247, 244, 227));
        btnreserv.setBorder(null);
        btnreserv.setContentAreaFilled(false);
        btnreserv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreservMouseClicked(evt);
            }
        });
        menus.add(btnreserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 400, -1, -1));

        btnsalle.setBackground(new java.awt.Color(247, 244, 227));
        btnsalle.setBorder(null);
        btnsalle.setContentAreaFilled(false);
        menus.add(btnsalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 560, -1, -1));

        btnstock.setBackground(new java.awt.Color(247, 244, 227));
        btnstock.setBorder(null);
        btnstock.setContentAreaFilled(false);
        menus.add(btnstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 720, -1, -1));

        btndeco.setBackground(new java.awt.Color(247, 244, 227));
        btndeco.setBorder(null);
        btndeco.setContentAreaFilled(false);
        btndeco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndecoMouseClicked(evt);
            }
        });
        menus.add(btndeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 960, -1, -1));

        getContentPane().add(menus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        titre.setBackground(new java.awt.Color(51, 51, 51));
        titre.setFont(new java.awt.Font("Noto Sans", 0, 40)); // NOI18N
        titre.setText("Nos Menus");
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 32, -1, -1));
        getContentPane().add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1201, 135, -1, -1));
        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 135, -1, -1));
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreservMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreservMouseClicked

     this.setVisible(false);
        new Reservation().setVisible(true);
    }//GEN-LAST:event_btnreservMouseClicked

    private void btnmenuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmenuonActionPerformed

    private void btndecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndecoMouseClicked
    this.dispose();
    }//GEN-LAST:event_btndecoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btndeco;
    public javax.swing.JButton btnmenuon;
    public javax.swing.JButton btnreserv;
    public javax.swing.JButton btnsalle;
    public javax.swing.JButton btnstock;
    public javax.swing.JLabel fond;
    public javax.swing.JLabel logo;
    public javax.swing.JLabel menu1;
    public javax.swing.JLabel menu2;
    public javax.swing.JPanel menus;
    public javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables

}
