/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Equipe02;

//import Equipe02.dao.ReservationDao;
import Equipe02.dao.ReservationDao;
import Equipe02.models.ReservationModel;
import com.mysql.cj.xdevapi.Table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ruban
 */
public class Reservation extends javax.swing.JFrame {

    private Object id = 1;


    /**
     * Creates new form reservation
     */
    public Reservation() {
        this.setUndecorated(true);
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menus = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnmenuon = new javax.swing.JButton();
        btnreserv = new javax.swing.JButton();
        btnsalle = new javax.swing.JButton();
        btnstock = new javax.swing.JButton();
        btndeco = new javax.swing.JButton();
        mainPanelReservation = new javax.swing.JPanel();
        reservationlabel = new javax.swing.JLabel();
        nbcouvlabel = new javax.swing.JLabel();
        nbtablelabel = new javax.swing.JLabel();
        heurelabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        serveurlabel = new javax.swing.JLabel();
        nomlabel = new javax.swing.JLabel();
        serveur = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        reserver = new javax.swing.JButton();
        nbcouverts = new javax.swing.JTextField();
        ntable = new javax.swing.JTextField();
        heure = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        menus.setBackground(new java.awt.Color(247, 244, 220));
        menus.setPreferredSize(new java.awt.Dimension(284, 1080));

        logo.setIcon(new javax.swing.ImageIcon("D:\\Cours\\Java\\Miam-S-Paradise\\src\\images\\LOGOMENUS.png")); // NOI18N

        btnmenuon.setBackground(new java.awt.Color(247, 244, 227));
        btnmenuon.setIcon(new javax.swing.ImageIcon("D:\\Cours\\Java\\Miam-S-Paradise\\src\\images\\Menus.png")); // NOI18N
        btnmenuon.setBorder(null);
        btnmenuon.setContentAreaFilled(false);
        btnmenuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuonMouseClicked(evt);
            }
        });
        btnmenuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuonActionPerformed(evt);
            }
        });

        btnreserv.setBackground(new java.awt.Color(247, 244, 227));
        btnreserv.setIcon(new javax.swing.ImageIcon("D:\\Cours\\Java\\Miam-S-Paradise\\src\\images\\reservbouton.png")); // NOI18N
        btnreserv.setBorder(null);
        btnreserv.setContentAreaFilled(false);
        btnreserv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreservMouseClicked(evt);
            }
        });
        btnreserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreservActionPerformed(evt);
            }
        });

        btnsalle.setBackground(new java.awt.Color(247, 244, 227));
        btnsalle.setIcon(new javax.swing.ImageIcon("D:\\Cours\\Java\\Miam-S-Paradise\\src\\images\\sallebouton.png")); // NOI18N
        btnsalle.setBorder(null);
        btnsalle.setContentAreaFilled(false);
        btnsalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalleMouseClicked(evt);
            }
        });
        btnsalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalleActionPerformed(evt);
            }
        });

        btnstock.setBackground(new java.awt.Color(247, 244, 227));
        btnstock.setIcon(new javax.swing.ImageIcon("D:\\Cours\\Java\\Miam-S-Paradise\\src\\images\\stockbouton.png")); // NOI18N
        btnstock.setBorder(null);
        btnstock.setContentAreaFilled(false);
        btnstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnstockMouseClicked(evt);
            }
        });
        btnstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstockActionPerformed(evt);
            }
        });

        btndeco.setBackground(new java.awt.Color(247, 244, 227));
        btndeco.setIcon(new javax.swing.ImageIcon("D:\\Cours\\Java\\Miam-S-Paradise\\src\\images\\decobtn2.png")); // NOI18N
        btndeco.setBorder(null);
        btndeco.setContentAreaFilled(false);
        btndeco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndecoMouseClicked(evt);
            }
        });
        btndeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menusLayout = new javax.swing.GroupLayout(menus);
        menus.setLayout(menusLayout);
        menusLayout.setHorizontalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmenuon)
                    .addComponent(btnreserv)
                    .addComponent(btnsalle)
                    .addComponent(btnstock)
                    .addComponent(btndeco))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menusLayout.setVerticalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmenuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreserv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnstock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndeco)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        mainPanelReservation.setBackground(new java.awt.Color(247, 244, 227));

        reservationlabel.setBackground(new java.awt.Color(51, 51, 51));
        reservationlabel.setFont(new java.awt.Font("Noto Sans", 0, 40)); // NOI18N
        reservationlabel.setText("Réservation");

        nbcouvlabel.setBackground(new java.awt.Color(51, 51, 51));
        nbcouvlabel.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        nbcouvlabel.setText("Nombre de couverts");

        nbtablelabel.setBackground(new java.awt.Color(51, 51, 51));
        nbtablelabel.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        nbtablelabel.setText("Numéro table");

        heurelabel.setBackground(new java.awt.Color(51, 51, 51));
        heurelabel.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        heurelabel.setText("Heure");

        datelabel.setBackground(new java.awt.Color(51, 51, 51));
        datelabel.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        datelabel.setText("Date");

        serveurlabel.setBackground(new java.awt.Color(51, 51, 51));
        serveurlabel.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        serveurlabel.setText("Serveur");

        nomlabel.setBackground(new java.awt.Color(51, 51, 51));
        nomlabel.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        nomlabel.setText("Nom client");

        serveur.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        serveur.setPreferredSize(new java.awt.Dimension(186, 45));

        nom.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        nom.setPreferredSize(new java.awt.Dimension(186, 45));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        date.setPreferredSize(new java.awt.Dimension(186, 45));

        reserver.setBackground(new java.awt.Color(247, 244, 227));
        reserver.setIcon(new javax.swing.ImageIcon("D:\\Cours\\Java\\Miam-S-Paradise\\src\\images\\btnreserv.png")); // NOI18N
        reserver.setBorder(null);
        reserver.setContentAreaFilled(false);
        reserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserverActionPerformed(evt);
            }
        });

        nbcouverts.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        nbcouverts.setPreferredSize(new java.awt.Dimension(186, 45));

        ntable.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        ntable.setPreferredSize(new java.awt.Dimension(186, 45));

        heure.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        heure.setPreferredSize(new java.awt.Dimension(186, 45));

        javax.swing.GroupLayout mainPanelReservationLayout = new javax.swing.GroupLayout(mainPanelReservation);
        mainPanelReservation.setLayout(mainPanelReservationLayout);
        mainPanelReservationLayout.setHorizontalGroup(
            mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelReservationLayout.createSequentialGroup()
                .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelReservationLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(nomlabel)
                        .addGap(141, 141, 141)
                        .addComponent(serveurlabel)
                        .addGap(170, 170, 170)
                        .addComponent(datelabel))
                    .addGroup(mainPanelReservationLayout.createSequentialGroup()
                        .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(mainPanelReservationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ntable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelReservationLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(heurelabel)
                                .addGap(150, 150, 150)
                                .addComponent(nbtablelabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelReservationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(serveur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelReservationLayout.createSequentialGroup()
                                .addComponent(nbcouverts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(reserver, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbcouvlabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelReservationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(reservationlabel)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        mainPanelReservationLayout.setVerticalGroup(
            mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelReservationLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomlabel)
                    .addComponent(serveurlabel)
                    .addComponent(datelabel))
                .addGap(18, 18, 18)
                .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serveur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heurelabel)
                    .addComponent(nbtablelabel)
                    .addComponent(nbcouvlabel))
                .addGap(18, 18, 18)
                .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ntable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nbcouverts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reserver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelReservationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(reservationlabel)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanelReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanelReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("reservationframe");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String url;
    private String username;
    private String password;

        
    
    private void reserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserverActionPerformed

    try{
        String url = "jdbc:mysql://mysql-thomas-messina.alwaysdata.net:3306/thomas-messina_miamsparadise";
        String username = "194765";
        String password = "MiamSParadise";
        Connection connection = DriverManager.getConnection(url, username, password);
        
    
           
        ReservationModel reservation = new ReservationModel();
        reservation.setNomClient(nom.getText());
        reservation.setNomClient(serveur.getText());
        reservation.setDate(date.getText());
        reservation.setHeure(heure.getText());
        reservation.setNomClient(ntable.getText());
        reservation.setNomClient(nbcouverts.getText());


        ReservationDao reservationDao = new ReservationDao(url, username, password);
        reservationDao.saveReservation(reservation);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
 
    }//GEN-LAST:event_reserverActionPerformed
    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void btndecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndecoMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btndecoMouseClicked

    private void btnstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstockActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnstockActionPerformed

    private void btnsalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalleActionPerformed

    private void btnreservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservActionPerformed
                   // TODO add your handling code here:
    }//GEN-LAST:event_btnreservActionPerformed

    private void btnreservMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreservMouseClicked
        this.setVisible(false);
        new Reservation().setVisible(true);
    }//GEN-LAST:event_btnreservMouseClicked

    private void btnmenuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuonActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_btnmenuonActionPerformed

    private void btndecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecoActionPerformed
        
    }//GEN-LAST:event_btndecoActionPerformed

    private void btnstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstockMouseClicked
        this.setVisible(false);
        new gestionstock().setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_btnstockMouseClicked

    private void btnsalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalleMouseClicked
        this.setVisible(false);
        new gestionsalle().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnsalleMouseClicked

    private void btnmenuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuonMouseClicked
        this.setVisible(false);
        new menus().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btnmenuonMouseClicked

    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btndeco;
    public javax.swing.JButton btnmenuon;
    public javax.swing.JButton btnreserv;
    public javax.swing.JButton btnsalle;
    public javax.swing.JButton btnstock;
    public javax.swing.JTextField date;
    public javax.swing.JLabel datelabel;
    public javax.swing.JTextField heure;
    public javax.swing.JLabel heurelabel;
    public javax.swing.JLabel logo;
    public javax.swing.JPanel mainPanelReservation;
    public javax.swing.JPanel menus;
    public javax.swing.JTextField nbcouverts;
    public javax.swing.JLabel nbcouvlabel;
    public javax.swing.JLabel nbtablelabel;
    public javax.swing.JTextField nom;
    public javax.swing.JLabel nomlabel;
    public javax.swing.JTextField ntable;
    public javax.swing.JLabel reservationlabel;
    public javax.swing.JButton reserver;
    public javax.swing.JTextField serveur;
    public javax.swing.JLabel serveurlabel;
    // End of variables declaration//GEN-END:variables
}
